### PR TITLE
Cdat logo

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa @aashish24 I don't think this needs much review

**Comment by doutriaux1** [comment]
new blines at: https://github.com/UV-CDAT/uvcdat-testdata/pull/183

**Comment by durack1** [comment]
@doutriaux1 looks neat.. We'll need to make sure that we're also pulling this across to other repos, I'm thinking the PCMDI/pcmdi_metrics#517 in particular

**Comment by danlipsa** [comment]
LGTM

**Comment by aashish24** [comment]
If okay I would change the name to cdat.png from logo.png (as logo is a very generic term) but I am fine either way. LGTM as well. I live the logo 👍

**Comment by doutriaux1** [comment]
@aashish24 it used to be named uvcdat.png I changed to something generic on purpose but I can rename no problem. Will do that.

**Comment by jypeter** [comment]
I like the characters, but what are the partly connected dots inside the **C** supposed to mean? They look nice as well anyway!

**Pull request merged**
