### PR TITLE
Issue 282 and 283 td improvments

### PR DESCRIPTION
**Pull request by doutriaux1**
@lee1043 @chengzhuzhang @danlipsa @aashish24 ready for review

### CODE REVIEW

**Comment by chengzhuzhang** [comment]
@doutriaux1  Thank you for working on these two issues! @lee1043 we can update the jupyter notebook once this is merged :)

**Comment by lee1043** [comment]
@doutriaux1 thanks for the improvement. Looks good to me, can't wait to test it.

**Comment by durack1** [comment]
@doutriaux1 is there a new test for this :)

**Comment by doutriaux1** [comment]
@durack1 nice catch I had forgotten to push it up!

**Pull request merged**
