### PR TITLE
Adds optional modal file for portrait plots

### PR DESCRIPTION
**Pull request by James-Crean**

### CODE REVIEW

**Comment by durack1** [comment]
@James-Crean nice, is there a demo hanging off a webserver somewhere to peak at?

@gleckler1 @doutriaux1

**Comment by James-Crean** [comment]
https://oceanonly.llnl.gov/crean2/plots/roadmap_amip_rms_xy.html

**Comment by gleckler1** [comment]
Beautiful!!!!

**Comment by jypeter** [comment]
What's this _modal file_ stuff? I can't access the demo from outside and see an image

**Comment by doutriaux1** [comment]
it's internal to PCMDI.

**Comment by doutriaux1** [comment]
@James-Crean I think I pushed the merged too quick, I tihnk you forgot to add it in setup.py, if you don't the file won't part of distributions.

**Comment by James-Crean** [comment]
This should be fixed in #288.

**Pull request merged**
