### PR TITLE
Fix isofill levels

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Please review. Where do I commit the new png and nc for the new testfile as well as changes to uvcdat/CMakeLists.txt?

**Comment by doutriaux1** [comment]
thanks @danlipsa please commit to the usual repo for baselines UV-CDAT/uvcdat-testdata and createa branch with this branch's name on the UVCDAT/uvcdat repo, that should trigger the test suite.

**Comment by danlipsa** [comment]
@doutriaux1 Thanks.
Here are the additional PR:
https://github.com/UV-CDAT/uvcdat-testdata/pull/155
https://github.com/UV-CDAT/uvcdat/pull/2124

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 The fix is the second commit. The first commit is identical to the one reversed.

**Comment by aashish24** [comment]
@danlipsa in theory the code looks good to me. Basically you are setting some valid value to hidden points so that scalar range does not change. @doutriaux1 can you confirm if this fixes the issue for you?

**Comment by danlipsa** [comment]
@aashish24 That is right. I also remove the globalid attribute and then add it back because otherwise RemoveDeletedCells does not remove the globalid associated with the deleted cells.

**Pull request merged**
