### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by embrown**
Adds a function and a dictionary in xmldocs.py to populate docstrings for many functions.
Swaps out previous docstrings for the populated docstrings.
Updates all :Example: entries to doctests.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@embrown some of these are corrected in my PR, maybe you can wait until mine is approved.

**Comment by durack1** [comment]
@embrown @doutriaux1 are there any pieces in this PR that could be repurposed to construct documentation across the other code bases UV-CDAT/cdms#13, UV-CDAT/cdutil#1 and UV-CDAT/genutil#2

**Comment by embrown** [comment]
@durack1 cdutil and genutil, no. There is not enough repetition in the existing docstrings. I would have to look at cdms and see if there's any cases where I could use a similar approach.

Mainly the documentation I am generating here is for functions like script(), create___() and get___(), because there was a lot of repetition between the respective docstrings, with only a few keywords that needed to be replaced.

**Comment by durack1** [comment]
@embrown, just curious do you have a docstring style that you'd be recommending in order to best document python functions across a suite of packages that will attempt to maintain forward compatibility? I've been following a sphinx-style format (the spyder IDE presents this as inline documentation in the GUI), but haven't done much investigation if this is the best format across software and platforms

**Comment by embrown** [comment]
@durack1 I haven't done much research in that regard either. I started documenting this stuff knowing next to nothing about Sphinx and RST format and just kind of learned along the way. 

If I could do it again, I would probably use NumPy or Google-style documentation. Apparently there's a Sphinx extension called [Napoleon](http://www.sphinx-doc.org/en/stable/ext/napoleon.html) that allows you to use those styles, and they are much easier to read than all of the :param: and :type: entries that vcs's documentation currently uses. Plus they allow for functions that have multiple return values (not a big deal with VCS, but I'm seeing a lot of functions with multiple returns in GenUtil/CDUtil).

**Comment by durack1** [comment]
Interesting, any chance you have good links to the NumPy or Google-style doc formats?

**Comment by embrown** [comment]
@durack1 [Google vs. NumPy](http://www.sphinx-doc.org/en/stable/ext/napoleon.html#google-vs-numpy)

**Comment by durack1** [comment]
@embrown great thanks!

**Pull request merged**
