### PR TITLE
commenting out until we understand exactly why it was here in the fir…

### PR DESCRIPTION
**Pull request by doutriaux1**
…st place

@aashish24 @sankhesh @embrown @danlipsa please review and comment on why this comment was put in the first place.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@aashish24 @embrown we could use something like that once we know why the warning was here for:
```python
import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()
```

**Comment by durack1** [comment]
@doutriaux1 I really think suppressing warnings is a bad idea, maybe use https://docs.python.org/2/library/warnings.html#the-warnings-filter the "once" option - so a warning is thrown, but it doesn't hijack the current session

**Comment by embrown** [comment]
@doutriaux1 no clue here. Never added any warnings to VCS when doing documentation.

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa it's good for review I think

**Pull request merged**
