### PR TITLE
Streamlines plus tests

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 What happened? All commits were squashed into one giant commit! I don't think we want that in this case, isn't it?

**Comment by doutriaux1** [comment]
@danlipsa we've been squashing for a while now. I personally really don't care feel free to revert and merge with all commits.

**Comment by danlipsa** [comment]
@doutriaux1 OK, I'll do that.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I remerged with with a merge commit instead of squashing everything.

**Pull request merged**
