### PR TITLE
Do not mark attribute as VECTORS so that are not removed.

### PR DESCRIPTION
**Pull request by danlipsa**
vtkTransformPolyData changes a VECTORS attribute from double to float
than vtkAppendPolyData removes that attribute because of non-matching
attributes (double and float).

### CODE REVIEW

**Comment by danlipsa** [comment]
Goes with
https://github.com/UV-CDAT/uvcdat-testdata/pull/185

**Comment by danlipsa** [comment]
Fixes
https://github.com/UV-CDAT/vcs/issues/184

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Please review.

**Comment by danlipsa** [comment]
@doutriaux1 ping

**Comment by danlipsa** [comment]
@doutriaux1 Only a few data files are downloaded. In particular, geos5-sample.nc is not. Do you know why? Thanks.

**Comment by danlipsa** [comment]
This seem to be the reason:
Share/test_data_files.txt

**Comment by doutriaux1** [comment]
@danlipsa we try to keep what the test suite needs as minimal as possible to fasten testing on ci

**Comment by doutriaux1** [comment]
@danlipsa if possible data that are already in the list you mentioned above

**Comment by danlipsa** [comment]
Sounds good, thanks.

**Comment by danlipsa** [comment]
@doutriaux1 I think this is ready.

**Pull request merged**
