### PR TITLE
ENH: Save pdf files compressed.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by aashish24** [comment]
@danlipsa is there a reason that we only compress for PDF ?

**Comment by danlipsa** [comment]
@aashish24 Because for the other formats it just zips the file, so you have to unzip it before you can view it.

**Comment by aashish24** [comment]
okay thanks @danlipsa

**Comment by aashish24** [comment]
LGTM :+1:

**Comment by doutriaux1** [comment]
@aashish24 wasn't this only supposed to be approved with https://github.com/UV-CDAT/uvcdat/pull/2146

**Comment by danlipsa** [comment]
@doutriaux1 It won't cause any harm without that. It will just save pdfs compressed (with the pdf.gz extension) You'll need the updated VTK to get .pdf extension.

**Pull request merged**
