### PR TITLE
Add streamline to graphicsmethodlist

### PR DESCRIPTION
**Pull request by danlipsa**
Such as boxfill, isofill, ...

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 Please review.

**Comment by doutriaux1** [comment]
@danlipsa this function already exist:
```python
import vcs
vcs.listelements()
```

**Comment by danlipsa** [comment]
@doutriaux1 vcs.listelements() lists everything in vcs.elements including colormaps, fonts, ... isn't it? I only want graphics methods.

**Comment by doutriaux1** [comment]
i see, let's add a keyword to listelements then
```python
vcs.listelements("graphicmethods")
```
and we're at it we can use the official names
```python
vcs.listelements("primary")  # graphic methods
vcs.listelements("secondary")  # fillarea, text, etc... see query.py for types
```

What do you think, I feel it's better to not multiply the already huge number of functions.

**Comment by doutriaux1** [comment]
@danlipsa actually we also already have the function as you want it
```python
import vcs
vcs.queries.graphicsmethodlist()
```

**Comment by danlipsa** [comment]
Oh, nice! I'll use that then.

**Comment by doutriaux1** [comment]
@danlipsa please make sure all gms are in, I think it might be missing streamlines for example. Thx.

**Comment by danlipsa** [comment]
@doutriaux1 I am off today, I'll do it on Monday.

**Comment by doutriaux1** [comment]
no worries. enjoy!

**Comment by danlipsa** [comment]
@doutriaux1 Don't forget this. The CIs complain about bare except which seems unrelated to this change.

**Comment by doutriaux1** [comment]
@danlipsa yep I have the except fixed in another branch (flake8 latest update complains about this now)

**Comment by danlipsa** [comment]
@doutriaux1 Don't forget to merge this. It's needed by vcs-js.

**Pull request merged**
