### PR TITLE
llvm seems to freak out on // builds changing to n = 1

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
@danlipsa mac passes BUT all vector baselines look wrong. Could you double check them please?

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 I looked over the baseline differences. 

https://github.com/UV-CDAT/uvcdat-testdata/pull/172
They look fine.

Indeed, some of the vector baselines are very different just because the glyphs are one or two pixels so they can and do disappear if the interpolation in the graphics driver is done differently.

The solution is to fix the vector plot such that, by default it shows a reasonable plot - we'll do that by computing the proper down-sampling of the data.
 https://github.com/UV-CDAT/uvcdat-testdata/pull/172

I hope to do this next time I work on vcs (vcs-js + another project in the queue). I'll talk to @aashish24 about that.

**Comment by doutriaux1** [comment]
@danlipsa ok so if you think it's ok I can go ahead and merge once the Linux baselines are up. I could also scale the vectors to be a bit bigger. I'll do that and start adding the `vector` attribute to the test, following up on your idea.

**Comment by danlipsa** [comment]
@doutriaux1 I would not do any scaling in the vector methods - I remember removing some scaling in the vector methods because I expect vectors to be a certain size based on the projection and viewport size. This is used to show the vector legend.

Its fine to resample in the test though, if you want to make the glyphs bigger. The proper solution is do random sampling similar with the basic streamlines.

**Pull request merged**
