### PR TITLE
fix #275

### LINKED ISSUE #275: Idea for canvas reinitialization: x.reinit()
Currently `removeobject` works for removing individual object or template, but I was thinking something like below, so everything can be easily removed but keep canvas alive so it can be re-used. 

```python
x=vcs.init()
x.plot(d)
x.reinit() ## Clear every objects in the canvas, remaining canvas alive
```

This would help when creating thousands of plots as @durack1 , @gleckler1 and I do, but memory usage is keep increasing because of user missed erase some of vcs object. @doutriaux1 What do you think?

### PR DESCRIPTION
**Pull request by doutriaux1**
@lee1043 @durack1 @danlipsa ready for review

### CODE REVIEW

**Comment by doutriaux1** [comment]
@durack1 @lee1043 this brutally removes EVERYTHING you created. I wonder if I should preserve methods that are in use on opened canvas

**Comment by durack1** [comment]
@doutriaux1 I think that having keyword args - so things to keep for e.g. would be a good thing

**Comment by doutriaux1** [comment]
@durack1 this is not really feasible, if you want to micro manage, then you need to do it properly or manually.

**Comment by lee1043** [comment]
@doutriaux1 Thanks for adding this `reset` capability. It looks good to me. I like [the way it works](https://github.com/UV-CDAT/vcs/blob/61af783946269e9d43d6b1bf3b5239fd70198098/vcs/manageElements.py#L53), which can be used for whole or for selected objects.

**Comment by durack1** [comment]
@doutriaux1 this is great, and as noted by @lee1043 you've managed to implement a number of keywords args, which solves my query above https://github.com/UV-CDAT/vcs/pull/281#issuecomment-350072585, so please merge away

**Pull request merged**
