### PR TITLE
Test for fillarea concave.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Goes with
https://github.com/UV-CDAT/uvcdat-testdata/pull/190

**Comment by danlipsa** [comment]
Fixes
https://github.com/UV-CDAT/vcs/issues/254

**Comment by doutriaux1** [comment]
Thanks @danlipsa this is great!

**Comment by danlipsa** [comment]
@doutriaux1 Not sure what's wrong with travis, circle seems fine.

**Comment by doutriaux1** [comment]
I know working on trying to get more info, all test seem to pass, yet travis says "no", might be a time limit.

**Comment by doutriaux1** [comment]
yep on mine i see:
The job exceeded the maximum time limit for jobs, and has been terminated.

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 @scottwittenburg I think this is ready

**Pull request merged**
