### PR TITLE
Update doc

### PR DESCRIPTION
**Pull request by doutriaux1**

### CODE REVIEW

**Comment by doutriaux1** [comment]
Finally got the doctest working and in the test suite.
@danlipsa @scottwittenburg @aashish24 please review.

**Comment by aashish24** [comment]
@doutriaux1 what is the best way to review this branch?

**Comment by doutriaux1** [comment]
@aashish24 few things:

* cd docs ; make html ; open _build/index.html
* cd docs ; make doctest
* review changes to the actual code I had to make in order for fix bug that the doctest  revealed.

**Comment by danlipsa** [comment]
@doutriaux1 Does this PR move the jupyter notebooks from uvcdat-site into vcs?
Is the doc built here saved somewhere? Do you have a URL?

**Comment by doutriaux1** [comment]
@danlipsa, yes that way they get linked automatically into the vcs documentation, see: https://uvcdat.llnl.gov/vcs/index.html

**Comment by doutriaux1** [comment]
@danlipsa I also have code to pickup automagicaly which section(s) should each jupyter notebook should be referenced from. See: https://uvcdat.llnl.gov/vcs/API/graphics/boxfill.html#jupyter-notebooks

**Comment by danlipsa** [comment]
Very nice! Would a good way to review this is going through the docs and make sure all notebooks work and the docs seem complete?

**Comment by doutriaux1** [comment]
@danlipsa that's a good question. All these notebooks have been reviewed when released. We might want (in a separate PR?) to add a mecanism to make sure all the nb can be run with current nightly. @mattben once this is in place we should apply it to our cron job to post the nightlies, that way notebooks in doc represent the latest version. e.g when we change defsaults, etc...

**Comment by durack1** [comment]
@doutriaux1 very nice!!

**Comment by durack1** [comment]
@doutriaux1 you might want to make the (C) update to current year -it's currently `© Copyright 2016, LLNL. Created using Sphinx 1.6.7. `

**Pull request merged**
