### PR TITLE
Window resize

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Goes with:
https://github.com/UV-CDAT/uvcdat-testdata/pull/166

@doutriaux1 This are fixes for the following tests on OSMesa:
test_vcs_png_window_resize
test_vcs_close

These are the current failures on my machine:
nightly-nox-20170412: no failures
nightly-20170407: 
test_vcs_png_window_resize.py
fails because it tries to resize to a size bigger than the screen size.

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 @sankhesh please review.

**Comment by danlipsa** [comment]
@doutriaux1 Don't forget to fix the BlueMarble.ppm issue
https://github.com/UV-CDAT/vcs/issues/163#issuecomment-292978212
I fixed it by hand in my installation.

**Comment by doutriaux1** [comment]
@danlipsa running the test suite on my mac and linux and reporting back to you

**Pull request merged**
