### PR TITLE
121 missing value opacity

### LINKED ISSUE #121: boxfill missing value does not respect opacity
```python
import vcs
import cdms2

f=cdms2.open(vcs.sample_data+"/clt.nc")

s=f("clt")
x=vcs.init()
x.plot(s)
s2=cdms2.MV2.masked_greater(s,50.)
gm =x.createboxfill()
gm.missing=[50,50,50,50]
x.plot(s2,gm)

raw_input("press enteR")
```

gives: 
crap

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes #121

### CODE REVIEW

**Comment by durack1** [comment]
@doutriaux1 if this can be added to the `patterns` branch and whacked into a `nightly` I'll give it a run with my failing script

**Comment by durack1** [comment]
@sankhesh thanks for looking at this, I'm looking forward to getting boxfill working with opacities

**Comment by sankhesh** [comment]
@danlipsa Please review

**Comment by sankhesh** [comment]
@durack1 Sure thing.

**Comment by doutriaux1** [comment]
@sankhesh thanks! @danlipsa I will let you double check the removehiddencellpoint section. It looks right to me, but I would feel better if you review it as well. Once you're happy with it please merge in master.

**Comment by sankhesh** [comment]
Thanks @danlipsa.

Just pushed the suggested changes.

**Comment by durack1** [comment]
@sankhesh it would be great to add a test for this, just so future changes (and similar weird behaviours) can be caught in by the test suite rather than merged

**Comment by sankhesh** [comment]
Good idea @durack1. I'll add it.

**Comment by sankhesh** [comment]
@doutriaux1 @durack1 Okay to merge?

**Comment by durack1** [comment]
@doutriaux1 are we good to go here? I would really like to get these graphics moving

**Comment by durack1** [comment]
@doutriaux1 just checking https://anaconda.org/uvcdat/vcs-nox/files should a new nightly appear automagically, or can you trigger one?

**Comment by durack1** [comment]
@doutriaux1 just checking https://anaconda.org/uvcdat/vcs-nox/files should a new nightly appear automagically, or can you trigger one?

**Pull request merged**
