### PR TITLE
Fix put png on canvas

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Goes with
https://github.com/UV-CDAT/uvcdat-testdata/pull/163

**Comment by danlipsa** [comment]
Fixes
https://github.com/UV-CDAT/vcs/issues/155

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Please review, See end of https://github.com/UV-CDAT/vcs/issues/155 for context.

**Comment by durack1** [comment]
@danlipsa @doutriaux1 I would love to try this out.. Is `nightly` a possiblity?

**Comment by danlipsa** [comment]
@durack1 Only after its merged.

**Comment by durack1** [comment]
@doutriaux1 great! So how do I check to see whether a new `vtk` nightly has been built? It seems that the [existing one is 12+ days old on `linux-64`](https://anaconda.org/uvcdat/vtk-cdat/files)

**Comment by doutriaux1** [comment]
@durack1 no need for a new vtk, I'll push a new vcs on conda right away

**Comment by durack1** [comment]
@doutriaux1 great, can you also kick off a new `vcs-nox` too? And what is `vcs-js`? Should that also be updated?

**Pull request merged**
