### PR TITLE
ENH: Add vector legend.

### PR DESCRIPTION
**Pull request by danlipsa**
Goes with
https://github.com/UV-CDAT/uvcdat-testdata/pull/169

### CODE REVIEW

**Comment by danlipsa** [comment]
Solves
https://github.com/UV-CDAT/uvcdat/issues/1975

**Comment by danlipsa** [comment]
@doutriaux1 @aashish24 @sankhesh Please review. This PR adds a vector legend to the vector plot.

**Comment by doutriaux1** [comment]
@danlipsa cicrcleci:
```
Ran 1 test in 4.795s
OK
Ran 175 tests, 5 failed (97.14% success)
Failed tests:
	tests/test_vcs_click_info.py
	tests/test_vcs_isoline_extend_attributes.py
	tests/test_vcs_isoline_width_stipple.py
	tests/test_vcs_vectors_robinson.py
	tests/test_vcs_vectors_scale_options.py
Packaged Result Info in: results_Darwin_distiller-build-84.local_2017-05-01_14:06.tar.bz2

bash ./scripts/circleci_mac.sh returned exit code 5
```
starting it on my mac now.

**Comment by danlipsa** [comment]
@doutriaux1 What is the easiest way to get that tar file? I suspect this is where the baselines and differences are.

**Comment by danlipsa** [comment]
@doutriaux1 I restarted circleci with ssh and downloaded the pngs for the failures. The usual platform differences for line stiples and vector differences because vectors are very small (dots). It would be nice to have a better default for the uniform sampling of vectors - it would get rid of this problem.

**Comment by doutriaux1** [comment]
in the dropbox folder
https://www.dropbox.com/home/Apps/CDATUpload

**Comment by doutriaux1** [comment]
@danlipsa if you use nox to generate the baselines we shouldn't have these error on cis, because they use nox as well.

**Comment by doutriaux1** [comment]
@danlipsa the click info one worries me a lot.

**Comment by doutriaux1** [comment]
test_vcs_vectors_robinson.py is suspicious on mac too around antarctica

**Comment by doutriaux1** [comment]
@danlipsa there is something wrong with the legend. Look for example at test_vector_robinson the legend (there should not be a box around it by the way) shows a very long arrow that supposedly is worth: 0.03m/s the, min/max of the plot indicate: -17 and 68 with a mean of 15.5
That means if the arrows should be way off the charts and outside the plot if .03 is alreadythat long!

**Comment by danlipsa** [comment]
> test_vcs_vectors_robinson.py is suspicious on mac too around antarctica
@doutriaux1 Good catch! I pushed a fix this morning.

> if you use nox to generate the baselines we shouldn't have these error on cis, because they use nox as well.
@doutriaux1 I'll build nox and update the baselines.

**Comment by danlipsa** [comment]
@doutriaux1 Ready to merge? All tests pass on nox.

**Comment by doutriaux1** [comment]
I'm restarting circle-ci, there was a "bug fix" for conda that broke our test download script....

**Pull request merged**
