### PR TITLE
Migrate test suite [WIP]

### PR DESCRIPTION
**Pull request by doutriaux1**
no review yet please

### CODE REVIEW

**Comment by aashish24** [comment]
Not reviewing the branch but +1 for circleci as it will make it easy to debug. Wondering about what we have to do test against UV-CDAT master for example.

**Comment by doutriaux1** [comment]
I"m transfering all test from uv-cdat/testing/vcs into vcs repo and using nose/unittest with some mulltiprocessing. Also rewriting the whole cdash swiping images bit... Lots of work...

**Comment by aashish24** [comment]
> I"m transfering all test from uv-cdat/testing/vcs into vcs repo and using nose/unittest with some mulltiprocessing. Also rewriting the whole cdash swiping images bit... Lots of work...

@doutriaux1 could you please share the vision to the rest of the team?

**Comment by doutriaux1** [comment]
the vision is to have each repo's test suite colocated within the repo. And also to have it unittest, which removes the cmake/ctest dependency. This allows for a much easier CI. uv-cdat repo will still be the top entry point to test all repos together (testing inter dependencies)

**Comment by aashish24** [comment]
@doutriaux1 how you are running tests locally? (basically missing modules such as image_compare)

**Comment by aashish24** [comment]
> @doutriaux1 how you are running tests locally? (basically missing modules such as image_compare)

nm. I am past that but I am not seeing any verbosity on my console with nose v2 option.

**Comment by aashish24** [comment]
> nm. I am past that but I am not seeing any verbosity on my console with nose v2 option.

Okay solved that, now looking a data not found related issue.

**Comment by aashish24** [comment]
@doutriaux1 I had a bad script that might have forced pushed the last commit. I fixed the problem on my end but just wanted to give you heads up.

**Comment by aashish24** [comment]
@doutriaux1 the aspect ratio baseline needs to be updated as it was not tested before (see cmake code from before)

#    cdat_add_test(test_vcs_aspect_ratio
  #  "${PYTHON_EXECUTABLE}"
  #  ${cdat_SOURCE_DIR}/testing/vcs/test_aspect_ratio.py
  #  ${cdat_SOURCE_DIR}/testing/vcs/test_aspect_ratio.py
  #  )

**Comment by doutriaux1** [comment]
@aashish24 cool. It's good we're spotting little things like this in the test suite!

**Comment by aashish24** [comment]
> @aashish24 test is not implemented correctly

@doutriaux1 since we have that bug anyways, I would think for now, lets keep that test in the failing folder. I will push a fix for the bg and pngReady then.

**Comment by aashish24** [comment]
@doutriaux1 are we getting slightly different baselines?

**Comment by doutriaux1** [comment]
@aashish24 I'm using vtk-cdat nightly because it has @sankhesh patterns in it and the nice pdf font.

**Comment by aashish24** [comment]
> @aashish24 I'm using vtk-cdat nightly because it has @sankhesh patterns in it and the nice pdf font.

Ah.. that's why. Okay I will update my VTK to the recent VTK which has @sankhesh and @danlipsa 's changes. I guess that's why the alignment is slightly off.

**Comment by aashish24** [comment]
@doutriaux1 in the mean time can you update the baseline I pushed to testdata (basic_text)

**Comment by doutriaux1** [comment]
@aashish24 please try to run the tests from the uv-cdat repo first. If they pass then that means your test needs tweaks not the baselines. Also try to run them using master. In theory 99% of test should pass w/o changes to the baselines. @danlipsa and @sankhesh both ran the test suite recently with success. So new baselines really shouldn't be an issue.
In cases where you really need a new baseline, feel free to update it yourself. But please use a mesa-based VTK under Linux since that's what the travis/circleci will be running.

**Comment by aashish24** [comment]
> @aashish24 please try to run the tests from the uv-cdat repo first. If they pass then that means your test needs tweaks not the baselines. Also try to run them using master. In theory 99% of test should pass w/o changes to the baselines. @danlipsa and @sankhesh both ran the test suite recently with success

@doutriaux1 I am using my new Mac for all my coding and test runs. I will check on my VTK sha and compare it with the one we have now in UV-CDAT master. 

@doutriaux1 I am using the uv-cdat master conda environment for all my tests runs (except that I am running them individually). The test suite reports them as success via run_tests.py. Most of the tests are passing for me but the ones with text alignments are off on my new MAC system. The rendering of the plot data seems to be fine on my system.

**Comment by aashish24** [comment]
@doutriaux1 @danlipsa I found the real issue. So the basic_text was not running for some time because the baseline name https://github.com/UV-CDAT/uvcdat/blob/master/testing/vcs/test_vcs_basic_text.py was not matching the baseline name in the uvcdat-testdata (https://github.com/UV-CDAT/uvcdat-testdata/blob/master/baselines/vcs/test_vcs_basic_text.png). And I think the much older baseline had alignment issue which @danlipsa fixed recently.

**Comment by mcenerney1** [comment]
STOOOOOOOOOOOOOP!

**Comment by williams13** [comment]
Ditto!

-Dean

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24 @danlipsa I've disabled the stickler-ci webhook. What on earth was that about? Who enabled this, and why do I have 300 emails in my inbox?

**Comment by doutriaux1** [comment]
@chaosphere2112 a little gift from our in-house `stickler` @durack1

**Comment by durack1** [comment]
@chaosphere2112 @doutriaux1 I mean who doesn't like to receive 300 emails over the lunch break?

**Pull request closed without merging**
