### PR TITLE
ENH: Add evenly spaced streamlines.

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
Works with: https://github.com/UV-CDAT/uvcdat-testdata/pull/170

**Comment by danlipsa** [comment]
@aashish24 Don't forget to give me a +2 on the vtk MR 😄 
https://gitlab.kitware.com/vtk/vtk/merge_requests/2943

**Comment by danlipsa** [comment]
@doutriaux1 I think everything should be ready for the evenly spaced streamlines. How do I push the new VTK to conda so that this MR gets tested?

**Comment by doutriaux1** [comment]
ok let's do this

**Comment by doutriaux1** [comment]
can you  post it to your channel for both mac and linux? Or do you need me to do this. Also edit .travis and circleci to use the -V option to let it know which VTK to use (channel/label)

**Comment by doutriaux1** [comment]
@danlipsa I wonder why cicrcleci passes though...

**Comment by danlipsa** [comment]
@doutriaux1 Probably its a good idea for you to do this - you have that old linux you build everything on. See the VTK SHA at the beginning of the PR. Good question about circleci. I was surprised about that as well.

**Comment by doutriaux1** [comment]
@danlipsa no pbm. Doing it. Will take a while to build though. What's the SHA1 you want?

**Comment by danlipsa** [comment]
1c03d1d03b1c12d99dd090ba4c5ca078e2d9612f

**Comment by doutriaux1** [comment]
thx. I'm on it.

**Comment by danlipsa** [comment]
Great, thanks!

**Comment by doutriaux1** [comment]
@danlipsa I updated the test suite to use your SHA1. It's running.

**Comment by doutriaux1** [comment]
@danlipsa 3 failures

**Comment by danlipsa** [comment]
@doutriaux1 This seems the wrong vtk-cdat: 7.1.0.2.10-py27_mesalib_0. I don't see the SHA in the name.

**Comment by doutriaux1** [comment]
I get installed a bit later look after python run_tests line
I does update

**Comment by danlipsa** [comment]
@doutriaux1 The error is
<pre>
Traceback (most recent call last):
  File "/home/travis/build/UV-CDAT/vcs/tests/test_vcs_vectors_robinson.py", line 42, in testVCSVectorsRobinson
    self.allTests(params=['streamline', 'colored', 'evenlyspaced'])
  File "/home/travis/build/UV-CDAT/vcs/tests/test_vcs_vectors_robinson.py", line 33, in allTests
    self.x.plot(u,v,V, bg=1)
  File "/home/travis/build/UV-CDAT/vcs/vcs/Canvas.py", line 2690, in plot
    a = self.__plot(arglist, keyargs)
  File "/home/travis/build/UV-CDAT/vcs/vcs/Canvas.py", line 4019, in __plot
    returned_kargs = self.backend.plot(*arglist, **keyargs)
  File "/home/travis/build/UV-CDAT/vcs/vcs/VTKPlots.py", line 619, in plot
    vtk_backend_grid, vtk_backend_geo, **kargs))
  File "/home/travis/build/UV-CDAT/vcs/vcs/vcsvtk/pipeline2d.py", line 326, in plot
    self._plotInternal()
  File "/home/travis/build/UV-CDAT/vcs/vcs/vcsvtk/streamlinepipeline.py", line 95, in _plotInternal
    streamer = vtk.vtkEvenlySpacedStreamlines2D()
AttributeError: 'module' object has no attribute 'vtkEvenlySpacedStreamlines2D'
</pre>
Which is consistent with having an old VTK which does not have this class. Are you sure the right VTK gets installed?

**Comment by doutriaux1** [comment]
Arg!!!!! I built the wrong SHA1

```
Package plan for installation in environment /home/travis/miniconda:
The following packages will be UPDATED:
    vtk-cdat: 7.1.0.2.10-py27_mesalib_0 uvcdat [mesalib] --> 7.1.0.2.10.2017.06.21.11.56.f02f455d3c34b27e594020271c96dc38238e1150-py27_mesalib_0 uvcdat/label/test [mesalib]
vtk-cdat-7.1.0 100% |###############################| Time: 0:00:01  61.88 MB/s
('Names:', ['tests/test_vcs_1D_datawc.py', 'tests/test_vcs_1D_datawc_missing.py', 'tests/test_vcs_1D_in_boxfill.py', 
```
Back in a few hours....

**Comment by doutriaux1** [comment]
@danlipsa only flake8 is left failing. ON the other hand circleci should fail but report pass. Looking into this.

**Pull request merged**
