### PR TITLE
Fixes issue with '.py' extension in script() functions

### LINKED ISSUE #103: '.py' extension on script functions not working
```python
>>> import vcs
>>> a=vcs.init()
>>> b=a.getboxfill()
>>> b.script('filename.py')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-89bbd0e0a46d> in <module>()
----> 1 b.script('filename.py')

/Users/brown308/anaconda/envs/2.8/lib/python2.7/site-packages/vcs/boxfill.pyc in script(self, script_filename, mode)
   1097             fp.write("%s.ext_1 = '%s'\n" % (unique_name, self.ext_1))
   1098             fp.write("%s.ext_2 = '%s'\n" % (unique_name, self.ext_2))
-> 1099             fp.write("%s.missing = %g\n" % (unique_name, self.missing))
   1100             fp.write(
   1101                 "%s.datawc_calendar = %g\n" %

TypeError: float argument required, not tuple
```
@doutriaux1 Didn't this used to work?

### PR DESCRIPTION
**Pull request by embrown**
Closes #103 
Fixes script() functions for:
       
* boxfill.py
* meshfill.py
* isofill.py
* textcombined.py
* texttable.py
* vector.py
    
Every function had a reference to color which was expected to be float(old color format), except vector, whose .line property had changed to .linetype, which was causing an error.

### CODE REVIEW

**Comment by aashish24** [comment]
thanks @embrown do we have a test for this?

**Comment by aashish24** [comment]
Looks reasonable to me 👍

**Comment by embrown** [comment]
@aashish24 Oh that's right! I forgot to write a test. I'll put one up there.

**Comment by aashish24** [comment]
LGTM ..

**Comment by aashish24** [comment]
@embrown do you want to merge this?

**Comment by embrown** [comment]
@aashish24 I haven't run the tests on vcs with this in place, so I was waiting for someone more official than myself to do so and make sure I didn't break anything.

**Comment by williams13** [comment]
Sam and/or Charles,

Can you take a look at this for Ed?

Thanks,
Dean

**Comment by embrown** [comment]
Thank you @williams13. I would have run the tests myself, but I'm not quite sure what the testing process with VCS is now, since the repo split.

**Comment by aashish24** [comment]
@embrown @chaosphere2112 or @danlipsa can run the tests (and answer any questions you may have). you can always ping me or @doutriaux1 as well.

**Comment by embrown** [comment]
@chaosphere2112 @doutriaux1 looks like maybe the levels are being recorded incorrectly as well. They're put in as a string literal and validation is raising an error with that. I'm going to try to track all of these down and resolve them in this PR.

**Comment by embrown** [comment]
@doutriaux1 @chaosphere2112, I'm finding a lot of bugs in the various script() functions.
I'm in the process of going through and fixing them. 
I'll ping you when everything's passing and I submit the PR.

**Comment by doutriaux1** [comment]
@embrown as far the .scr goes we should deprecate the saving of them if not done already. We should focus on .json ones as far as script goes, and simply reading in OLD scr (as in any recent function would not be in)

**Comment by embrown** [comment]
@doutriaux1 Yeah, the SCR deprecation warnings have been in. 
I'm going through and addressing errors with how the python files are written out. 
It's obviously something not used much, since there don't seem to be any outstanding issues on the fact that the python scripts created don't work. But @chaosphere2112 indicated it is something he needs working, so I'm gonna fix it.

**Comment by embrown** [comment]
@doutriaux1, with a fair bit of help from @chaosphere2112 I was able to get the script() functions working for python files. They produce valid python scripts, those scripts run correctly with vcs.scriptrun(). I'll push my changes to the test that validates the object created from scriptrun() are identical to those on which script() was called.

**Comment by embrown** [comment]
@doutriaux1 @chaosphere2112 , This is done and should be merge-able. Once it's merged, All of the tests I'm adding to the vcs test suite today *should* work.

**Comment by doutriaux1** [comment]
@embrown sounds good. I will let @chaosphere2112 some time to review your changes since he requested them. How do you run the documentation test suite again? I would like to add it to travis.yaml eventually.

**Comment by embrown** [comment]
@doutriaux1 we're working on building the documentation tests into the vcs test suite, so it should just be run every time the vcs tests are run.

**Comment by doutriaux1** [comment]
@embrown if you're already doing it then all the merrier for me!

**Comment by embrown** [comment]
@doutriaux1 I'm working on it. I've got a PR submitted for the initial test (just tests docstrings from vcs.queries because those all pass without issue), and I'll be adding more tests onto that before I leave today. When I push my final changes to https://github.com/UV-CDAT/uvcdat/pull/2151, I will add a comment listing which branches need to be merged before all the new tests *should* (theoretically) pass.
It will probably still need a little work after I leave to get it smoothly integrated into the suite.

**Comment by aashish24** [comment]
@embrown any update on this branch? Are we just waiting on the review?

**Comment by embrown** [comment]
@aashish24 not sure. My internship ended in January, so I think the question would be better directed to @doutriaux1.

**Comment by aashish24** [comment]
> @aashish24 not sure. My internship ended in January, so I think the question would be better directed to @doutriaux1.

thanks @embrown @doutriaux1 could you please review this branch as I am less familiar with this code but I can attempt to review if no one else does.

**Pull request merged**
