### PR TITLE
2072 export patterns as vectors

### PR DESCRIPTION
**Pull request by sankhesh**
Fixes UV-CDAT/uvcdat#2072

### CODE REVIEW

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24 @williams13 @bonfils2

**Comment by doutriaux1** [comment]
thanks @sankhesh. reviewing now.

**Comment by sankhesh** [comment]
Thanks @doutriaux1. I'm working on fixing the tests too.

**Comment by doutriaux1** [comment]
@sankhesh 
```python
import vcs,cdms2
f=cdms2.open(vcs.sample_data+"/clt.nc")
s=f("clt")
x=vcs.init()
gm = x.createboxfill()
gm.fillareastyle
gm.fillareastyle = "hatch"
gm.fillareaindices = [ 1,2,3,4,5]
gm.boxfill_type="custom"
x.plot(s,gm)
```

gives:
bad

preceded with thousands of:

```
ERROR: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkImplicitDataSet.cxx, line 64
vtkImplicitDataSet (0x3fd2eb0): Can't evaluate function: either data set is missing or data set has no point data

ERROR: In /export/doutriaux1/anaconda2/conda-bld/work/Common/DataModel/vtkImplicitDataSet.cxx, line 64
vtkImplicitDataSet (0x3fd2eb0): Can't evaluate function: either data set is missing or data set has no point data

```

**Comment by doutriaux1** [comment]
isofill works, but @bonfils2 needs boxfill

**Comment by sankhesh** [comment]
@doutriaux1 Looking into it now.

**Comment by doutriaux1** [comment]
@sankhesh there are still some weirdness, plotting an isoline on top of the isofill heps see what a happens at the intersection, the following is a screenshot of of pdf zoomed into a chrome window.

Notice the green horizontal lines around 40N latitude, why are they all chopped up? Like ants ate part of them.

[iso.pdf](https://github.com/UV-CDAT/vcs/files/529918/iso.pdf)

**Comment by sankhesh** [comment]
@doutriaux1 The clipping algorithm seems not so perfect. @aashish24 and I spoke a little about these issues and I'll look into it in the next iteration. Let me fix boxfill plot issues first.

**Comment by sankhesh** [comment]
After latest set of changes, hatches/patterns work for boxfill plots. See example file.

[test_fillarea.pdf](https://github.com/UV-CDAT/vcs/files/530230/test_fillarea.pdf)

screenshot from 2016-10-14 14-46-44

**Comment by sankhesh** [comment]
@doutriaux1 I fixed the test baselines as well. Can we merge this branch so that @bonfils2 can use this code? It works fine for boxfill patterns and hatches.

Regarding clipping issues with isofill plots, Will is working on a filter that would provide the accuracy we need. Once that is ready I can incorporate it in our workflow.

**Comment by doutriaux1** [comment]
@sankhesh I will install your branch locally

**Comment by doutriaux1** [comment]
I'd rather wait for your clipping fixes

**Comment by sankhesh** [comment]
A-ok

**Comment by doutriaux1** [comment]
@sankhesh it's looking much better, please consider the following scrit:
```python
import cdms2,vcs,MV2,os
f=cdms2.open(os.path.join(vcs.sample_data,"clt.nc")
s=f("clt")
iso = vcs.createboxfill()
box = vcs.createboxfill()
mask = MV2.greater(s,75)
x=vcs.init(geometry=(1200,800))
box.boxfill_type = "custom"
box.fillareastyle = "hatch"
box.fillareaindices = [10,]
box.levels=[0.5,1.5]
box.fillareacolors = ["black"]
x.plot(s,iso)
x.plot(mask.astype("f"),box)
x.svg("celine_pattern")
x.postscript("celine")
raw_input("Press enteR")
```

clipping is not quite matching the boxfill area
pdf is ok svg as well but postscript files are not respecting the transparency it shows up as white.
[celine.ps.zip](https://github.com/UV-CDAT/vcs/files/556360/celine.ps.zip)

**Comment by doutriaux1** [comment]
Actually pdf from RH6 opened on Mac give us:
with no patterns in it.

[AL1Fa_map11a_hfls_F_JFM_4off.pdf](https://github.com/UV-CDAT/vcs/files/556478/AL1Fa_map11a_hfls_F_JFM_4off.pdf)

```
An error exists on this page. Acrobat may not display the page correctly. Please contact the person who created the PDF document to correct the problem.
```

**Comment by durack1** [comment]
@doutriaux1 interestingly that file opens in Preview on OS X 10.11.6..

**Comment by sankhesh** [comment]
@doutriaux1 Based on [this](http://stackoverflow.com/questions/29321707/can-transparency-be-used-with-postscript-eps) it seems like postscript does not support transparency. Was it supported earlier?

**Comment by doutriaux1** [comment]
@sankhesh all output should be the same. I'm not sure what it was doing earlier because nobdy used it really. Anyhow I'm attaching a trimmed down version of @bonfils2 script to help you. Notice that setting the color to "red" or [100,0,0,50] does not appear to affect pdf output at all (are we ignoring opacity in favor of fillareaopacity attribute?) Also different pattern seem to have different thickness and slightly different clipping.
Thanks
[patterns.zip](https://github.com/UV-CDAT/vcs/files/556661/patterns.zip)

**Comment by doutriaux1** [comment]
@durack1 yes opens for me too, but I think @bonfils2 has adobe reader installed.

**Comment by sankhesh** [comment]
Thanks for the pared down script @doutriaux1 :+1:
I'll take a look.

**Comment by doutriaux1** [comment]
@sankhesh there's definitely clipping issues left, look at the band for pattern 9 they should stop exactly at the limit of the box, but they're not, they look like they have been trimmed to some sort of interpolation line.

**Comment by sankhesh** [comment]
Goes with VTK branch @ https://gitlab.kitware.com/vtk/vtk/merge_requests/2084

**Comment by doutriaux1** [comment]
@aashish24 @sankhesh I'm buulding against @aashish24 branch, do I need to first merge them both together?

**Comment by aashish24** [comment]
@doutriaux1 I have updated my VTK branch with https://gitlab.kitware.com/vtk/vtk/merge_requests/2084

**Comment by aashish24** [comment]
@sankhesh can you post your update here so that we all know what's the current status is?

**Comment by sankhesh** [comment]
I've attached a pdf output of the latest code.
[test_fillarea (1).pdf](https://github.com/UV-CDAT/vcs/files/651899/test_fillarea.1.pdf)

Almost all clipping issues have been resolved barring one. The current issue we're looking into is specific to the pattern in the image below:

selection_004 1

You can see that the inner regions of the pattern somehow become distorted.

**Comment by williams13** [comment]
Sankhesh, this is much better! Excellent Progress! Can we get this into the next release?

Thanks and best regards,
Dean

**Comment by sankhesh** [comment]
@williams13 Yes, we are close. One other thing that I'll look into next would be to support custom fillarea objects as patterns.

**Comment by williams13** [comment]
Excellent!

With the smaller sized PDF output, these two fixes will make a huge difference. :-)

Best regards,
Dean

**Comment by durack1** [comment]
@sankhesh this looks like a great jump forward, looking to see this land in the next release!

**Comment by aashish24** [comment]
@sankhesh I believe Will have fixed the last known bug? Is that correct.

**Comment by sankhesh** [comment]
@aashish24 We merged the fix for the clipping bug to VTK proper late yesterday. I am testing it with the cookie cutter today. Hopefully we'll be able to merge the cookie cutter branch to VTK and use the new VTK with UV-CDAT today.

**Comment by sankhesh** [comment]
@doutriaux1 @aashish24 I've reviewed Will's cookie cutter branch and the fix for the clipping bug. These branches have been merged to VTK master. I guess we can bump up the UV-CDAT/VTK fork to latest master and merge this PR. What do you say?

**Comment by danlipsa** [comment]
@sankhesh Do you mind rebasing on master and squashing your commits. I would like to use your branch for the context2d work. Did you run the tests and update uvdat-testdata?

**Comment by doutriaux1** [comment]
@sankhesh @danlipsa as soon as you have a sha1 for us to try please let us know. I'm excited this is finally getting close to a conclusion!

**Comment by sankhesh** [comment]
@danlipsa Just rebased the branch on master

**Comment by durack1** [comment]
@sankhesh @danlipsa @doutriaux1 excellent, looking forward to taking this new functionality for a test drive!

**Comment by doutriaux1** [comment]
@sankhesh running with a nightly build of VTK and your branch's HEAD I get:
```
doutriaux1@crunchy:[Patterns]:[11546]> python patterns.py 
Traceback (most recent call last):
  File "patterns.py", line 15, in <module>
    import vcs, time, string
  File "/export/doutriaux1/anaconda2/envs/Patterns_New-nox/lib/python2.7/site-packages/vcs/__init__.py", line 59, in <module>
    import Canvas  # noqa
  File "/export/doutriaux1/anaconda2/envs/Patterns_New-nox/lib/python2.7/site-packages/vcs/Canvas.py", line 27, in <module>
    from VTKPlots import VTKVCSBackend
  File "/export/doutriaux1/anaconda2/envs/Patterns_New-nox/lib/python2.7/site-packages/vcs/VTKPlots.py", line 5, in <module>
    import vcs2vtk
  File "/export/doutriaux1/anaconda2/envs/Patterns_New-nox/lib/python2.7/site-packages/vcs/vcs2vtk.py", line 1423
    if act is not None:
                      ^
SyntaxError: invalid syntax
```

**Comment by doutriaux1** [comment]
the issue is actually line 1416

**Comment by sankhesh** [comment]
@doutriaux1 Please reset the branch to commit f53996f. I am looking at an issue I found and the head is a WIP commit that I plan to clean up once I've fixed the issue.

**Comment by doutriaux1** [comment]
@sankhesh with that commit, generating files on linux (mesa build) and transfering the file to my mac. Opening with adobe reader I get no pattern in Adobe see:
bad_patterns
Thy look ok in Apple's Preview though
ps files are opened in PReview and look different but correct:
patterns_index_10_from_postscript

**Comment by danlipsa** [comment]
@doutriaux1 @williams13 @aashish24 I tried @sankhesh branch, commit 57c76a61505ade597c9bf0892d43bebfc6b8556a from Jan 26 and generated the following PDF.

@doutriaux1 Can you confirm this? I think you might have tried an older branch.

[patterns_index_10.pdf](https://github.com/UV-CDAT/vcs/files/740173/patterns_index_10.pdf)
These are my results.
Mac
------
Preview: It looks fine and is fast
Acrobat Reader: It looks fine but is slow to render.
Linux
-------
okular: I looks fine and is fast
evince: It does not show colors
I could not install Acrobat Reader on my Linux machine as it is not supported, and Adobe does not offer it for download since 2014 - I tried some third party repos but could not make it work. For more info see the following URL:
https://en.opensuse.org/Adobe_Reader#Adobe_Reader_9_under_Linux

**Comment by aashish24** [comment]
@doutriaux1 @williams13 as per my understanding, the known issues with patterns are fixed with this branch. The PDF issue is a separate issue so regardless of @danlipsa's results, if there are no known issues, I would suggest we merge this branch and fix any new PDF or Pattern issue in a separate branch. Does it makes sense? 

Thanks,

**Comment by doutriaux1** [comment]
@sankhesh what's the difference between this PR and the one you just merged?

**Comment by durack1** [comment]
@danlipsa here is how things look on a patched up `OS X 10.11.6`, so:
Preview 8.1:
preview8 1
And Acrobat 2015.023:
acrobat2015 023
For reference, it takes a while for Acrobat to "build" the image, but with Preview it's an instantaneous view

**Comment by doutriaux1** [comment]
I see the other one was the opacity issue correct?

**Comment by doutriaux1** [comment]
@durack1 yes I think the goal is to get Preview work best, because it's the standard Mac tool.

**Comment by danlipsa** [comment]
@doutriaux1 Yes, the other one was the test and baselines for the opacity issue. You only merged vcs.

**Comment by danlipsa** [comment]
@durack1 @doutriaux1 Do the generated patterns look right to you? Any other issues with this branch?

**Comment by doutriaux1** [comment]
@danlipsa can I use VTK nightly from 1/20 ? Or do I need to build from current VTK master?

**Comment by danlipsa** [comment]
@doutriaux1 I rebuild with the latest master, but I spoke with @sankhesh and the relevant merges were on 1/13. So your 1/20 should be OK. @sankhesh has to update the baselines for the patterns and he will run all tests and post the VTK sha he run the tests with.

**Comment by zshaheen** [comment]
Hi guys. I'm on the latest code in master for vcs and the 1.20.2016 nightly for vtk. When I do `textAsPaths=False`, I get the following [image](https://github.com/UV-CDAT/vcs/files/740833/test-messedup.pdf). You can obviously tell that the text is unaligned, but the file size is ~800KB and that's great.

Now without setting `textAsPaths=False`, the image is perfect and is this [one](https://github.com/UV-CDAT/vcs/files/740840/test.pdf). The file size is ~2.6MB however.

It would be nice to fix this issue, so vcs can match matplotlib.

**Comment by doutriaux1** [comment]
@aashish24 @danlipsa please talk with @dlonie and take a look at https://github.com/UV-CDAT/uvcdat/issues/1527 https://github.com/UV-CDAT/uvcdat/issues/1537 and especially take a look and use @jypeter script at: https://github.com/UV-CDAT/uvcdat/issues/1077

**Comment by durack1** [comment]
@danlipsa @doutriaux1 @aashish24 @zshaheen @sankhesh there were some open issues UV-CDAT/uvcdat#1079 and UV-CDAT/uvcdat#1080 that provide examples that are likely relevant to the text alignment, and also UV-CDAT/uvcdat#1537 which was the discussion about text as paths (as @doutriaux1 said)

**Comment by sankhesh** [comment]
@doutriaux1 Could you please review the latest HEAD of this branch?

**Comment by aashish24** [comment]
thanks @sankhesh. I do not see new updated baselines. Should I expect new ones?

**Comment by doutriaux1** [comment]
@sankhesh on it now.

**Comment by bonfils2** [comment]
@sankhesh @aashish24 @doutriaux1 
We just checked with Charles. Unfortunately, we are not able to obtain the same patches (size) that we used to obtain before (figures submitted now). I cannot see the hatching either anymore. Please compare the two figures: map13a for the old version; map13z for the new version. That makes me sad... Thanks!

[PAL1Fa_map13z_pr_Fpradveg_JFM_4on.pdf](https://github.com/UV-CDAT/vcs/files/749073/PAL1Fa_map13z_pr_Fpradveg_JFM_4on.pdf)
[PAL1Fa_map13a_pr_Fpradveg_JFM_4on.pdf](https://github.com/UV-CDAT/vcs/files/749075/PAL1Fa_map13a_pr_Fpradveg_JFM_4on.pdf)

**Comment by doutriaux1** [comment]
@sankhesh we used vtk-cdat-nox (mesa-built) to produce these because using the regular vtk-cdat seg faults instantly these days with X forwarding or VNC client.

**Comment by aashish24** [comment]
@bonfils2 @sankhesh looks like they are collapsing. I see some sort of red patches in the new one fused together. I guess they are the effect of @sankhesh scaling them but that does not explain why  they do not cover the same region. I am surprised since the baselines looking reasonable. I doubt that it is a mesa issue though since patterns are geometries however the depth is probably messed up.

**Comment by doutriaux1** [comment]
@sankhesh we did get an error for subsequent figures in `fillarea.py` about yres being 0.

**Comment by sankhesh** [comment]
@doutriaux1 I haven't come across the issue yet but as @aashish24 mentioned, it could be because of the scaling of the glyphs. I'll try reproducing the issue on my end as well.

**Comment by sankhesh** [comment]
@doutriaux1 @bonfils2 @aashish24 

I just pushed some more changes to the branch.
The biggest change would be the addition of two new parameters called `fillareapixelspacing` and `fillareapixelscale`. 


- `fillareapixelspacing` should be a two element list of ints which defines the spacing in X and Y in screen pixel space between each individual pattern element. Default value is [10, 10]

- `fillareapixelscale` is a scaling factor and determines how big the individual pattern elements will be on screen. Default value is 7.5

Using the defaults of [10, 10] and 7.5, I get the following file which has merged and blocky patterns:

vtk gl2ps export - 10x10_10

However using values of [4, 4] and 4.0, I get:

vtk gl2ps export 4x4_4

The new PDF file is here:
[patterns_index_10_4x4_4.pdf](https://github.com/UV-CDAT/vcs/files/751656/patterns_index_10_4x4_4.pdf)

**Comment by aashish24** [comment]
@sankhesh @williams13 this is great. Would it be possible to come up with a reasonable default automatically? so with [4, 4] and 4 I would expect (for a square pattern) that I will not have any gap. Since if I draw them at 0, 4, 8, 12th pixel position, and each of them are 4 units wide, then no gap will remain. Or do you use these numbers like this: 

* draw at 0 next one at 8 (since you want 4 pixel gap)?

**Comment by durack1** [comment]
@jypeter can you provide the scripts that generated the plots in UV-CDAT/uvcdat#1080? It would be great to add these into the test suite..

@sankhesh the examples (and the scripts included in the comments of @jypeter) for both https://github.com/UV-CDAT/uvcdat/issues/1077#issue-58886624 and https://github.com/UV-CDAT/uvcdat/issues/1079#issue-58918126 would also be great tests to add to the test suite..

**Comment by jypeter** [comment]
@durack1 I'll see if I can produce a stand-alone version of the script+data

**Comment by sankhesh** [comment]
@aashish24 

Yes, having a (4,4) spacing and a 4 pixel scale would mean no gaps when using a square pattern. The example in https://github.com/UV-CDAT/vcs/pull/23#issuecomment-277375144  is a not a square but a dash. Thats why you see gaps.

If required, we can add a loop that goes over all the viewports in the render window and chooses appropriate values. However, that would be messy and add another layer of computation before the actual plot. The values I have as defaults consider a single plot within a 1200 x 1091 pixel render window (default size for vcs tests). Even if we scale the `fillareapixelspacing` according to the render window size, there could be multiple mini plots (e.g. @bonfils2's example has 8 mini plots) and it would still look blocky. 

@durack1 @jypeter Are the markers in https://github.com/UV-CDAT/uvcdat/issues/1080 plots generated using the fill area pattern code?

**Comment by jypeter** [comment]
@sankhesh the markers I use are "regular" old-fashioned vcs markers

```
deep_marker = x.createmarker('deep_plot')
# Plot the data and model points
deep_marker.x = marker_x_list
deep_marker.y = marker_y_list
deep_marker.type = marker_s_list
deep_marker.color = marker_c_list
deep_marker.size = marker_sz_list

x.plot(deep_marker)
```

**Comment by bonfils2** [comment]
Thanks, there is improvement! I am now using [3,3] for the spacing, and 2 for the scale. The patterns are well separated and we can see the colors between lines. The lines, unfortunately, are broken (discontinued). Please see attached picture over western USA. 
untitled

**Comment by aashish24** [comment]
> The lines, unfortunately, are broken (discontinued). Please see attached picture over western USA.

I believe that the pattern is like that only. See the baseline here: https://raw.githubusercontent.com/UV-CDAT/uvcdat-testdata/e1719bf264d1027ae1c9b0154ed032aa126c8ba4/baselines/vcs/test_vcs_isofill_hatch_SH_-180_180.png

But may be @doutriaux1 or @sankhesh can shed more light on it.

**Comment by sankhesh** [comment]
@bonfils2 The patterning code essentially creates a bunch of points at a distance of `fillareapixelspacing` apart and then replaces the point with the pattern object. In this case, with a dash. For making it continuous, you'd have to use a `fillareapixelscale` of 3.

**Comment by doutriaux1** [comment]
@sankhesh this whole spacing/scale thing is quite mysterious to new users, do you think we could have a wiki page (or even better a jupyter notebook) that explains how all of this works? Thanks.

**Comment by aashish24** [comment]
> @sankhesh this whole spacing/scale thing is quite mysterious to new users, do you think we could have a wiki page (or even better a jupyter notebook) that explains how all of this works? Thanks.

+1

Also, @sankhesh and I talked about come up with reasonable default based on the viewport size of each plot. So by default users should be something very close to ideal and then the API can provide an option to tweak them if necessary.

**Comment by sankhesh** [comment]
@doutriaux1 Sure, I'll add some documentation on the wiki and figure out the jupyter notebook thing.

@aashish24 Change 77fc710 adds the reasonable defaults calculation based on the render window size. Note that adding a per-viewport calculation would change how the patterns look between individual plots and even the legend. 

I need to add one final change for making the legend work with these new parameters and add new baselines.

**Comment by sankhesh** [comment]
@aashish24 @doutriaux1 Take a look at the new baselines @ UV-CDAT/uvcdat-testdata#158 

The legend / colorbar pattern scale issues have been fixed. 

I have a [merge request](https://gitlab.kitware.com/vtk/vtk/merge_requests/2480/) in VTK that fixes the weird transparency issue.

Once the VTK change is merged, I'd say lets merge this branch. What do you think?

**Comment by aashish24** [comment]
@doutriaux1 @williams13 can you approve this branch and have us merge it? If there any other  minor issues or feature, we can do in a separate PR?

**Comment by doutriaux1** [comment]
@aashish24 is the VTK branch from @sankhesh in VTK master? If not can we put it into our VTK/master?

I can't really approve until we can access the bug fix.

**Comment by aashish24** [comment]
> @aashish24 is the VTK branch from @sankhesh in VTK master? If not can we put it into our VTK/master?

the plan is to have the branch merged into VTK master today and yes I will recommend not merging it until then but it would be good to have you look at it and run it if needed.

**Comment by aashish24** [comment]
@sankhesh make sure to ping Will as I do not think it should take him long time to approve the VTK branch. 

@doutriaux1 after we get the VTK branch merged and you are happy with this branch, for any minor issue let's create another PR so that we can get majority of improvements.

**Comment by sankhesh** [comment]
@aashish24 @doutriaux1 The VTK MR is merged.

**Comment by aashish24** [comment]
Great @sankhesh!

**Comment by aashish24** [comment]
ping @doutriaux1 @williams13 VTK branch is merged into VTK master.

**Comment by doutriaux1** [comment]
built it, i'm having issues with test suite, but you can use the linux build from my channel `doutriaux1`

**Comment by aashish24** [comment]
> built it, i'm having issues with test suite, but you can use the linux build from my channel doutriaux1

@doutriaux1 not sure if you are asking @sankhesh to do something or just stating the fact.

**Comment by doutriaux1** [comment]
stating. Should be able to merge early next week

**Comment by aashish24** [comment]
> stating. Should be able to merge early next week

Ok. thanks.

**Comment by sankhesh** [comment]
@doutriaux1 @williams13 Were you able to test this branch?

**Comment by doutriaux1** [comment]
@sankhesh I'll test it no and merge in

**Pull request merged**
